In [ ]:
class Shape:
    def __init__(self, color, filled):
        self.color = color
        self.filled = filled
    def get_info(self):
        fill_status = "filled" if self.filled else "not filled"
        print(f"Color: {self.color}, Status: {fill_status}")

class Rectangle(Shape):
    def __init__(self, color, filled, length, width):
        super().__init__(color, filled)
        self.length = length
        self.width = width
    def calculate_area(self):
        return self.length * self.width

rectangle = Rectangle("Blue", True, 5, 3)
rectangle.get_info()
print(f"Area: {rectangle.calculate_area()}")
print("Name: Aanit Brahma")
print("Roll Number: 2430601")

Color: Blue, Status: filled
Area: 15
Name: Aanit Brahma
Roll Number: 2430601

In [ ]:
class Vehicle:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year
    def display_info(self):
        print(f"Make: {self.make}, Model: {self.model}, Year: {self.year}")

class Car(Vehicle):
    def __init__(self, make, model, year, mileage):
        super().__init__(make, model, year)
        self.mileage = mileage
    def display_info(self):
        super().display_info()
        print(f"Mileage: {self.mileage} km")

car = Car("Toyota", "Corolla", 2020, 15000)
car.display_info()
print("Name: Aanit Brahma")
print("Roll Number: 2430601")

Make: Toyota, Model: Corolla, Year: 2020
Mileage: 15000 km
Name: Aanit Brahma
Roll Number: 2430601

In [ ]:
class Animal:
    def sound(self):
        print("This animal makes a sound.")

class Dog(Animal):
    def sound(self):
        print("Dog: Woof Woof!")

class Cat(Animal):
    def sound(self):
        print("Cat: Meow Meow!")

dog = Dog()
dog.sound()

cat = Cat()
cat.sound()

print("Name: Aanit Brahma")
print("Roll Number: 2430601")

Dog: Woof Woof!
Cat: Meow Meow!
Name: Aanit Brahma
Roll Number: 2430601

In [ ]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    def introduce(self):
        print(f"Name: {self.name}, Age: {self.age}")

class Student(Person):
    def __init__(self, name, age, student_id):
        super().__init__(name, age)
        self.student_id = student_id
    def introduce(self):
        super().introduce()
        print(f"Student ID: {self.student_id}")

student = Student("Aanit Brahma", 19, "2430601")
student.introduce()
print("Name: Aanit Brahma")
print("Roll Number: 2430601")

Name: Aanit Brahma, Age: 19
Student ID: 2430601
Name: Aanit Brahma
Roll Number: 2430601

In [ ]:
class BankAccount:
    def __init__(self, account_number, balance):
        self.account_number = account_number
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount
        print(f"Deposited: {amount}, New Balance: {self.balance}")

    def withdraw(self, amount):
        if amount > self.balance:
            print("Insufficient funds!")
        else:
            self.balance -= amount
            print(f"Withdrawn: {amount}, Remaining Balance: {self.balance}")

class SavingsAccount(BankAccount):
    def __init__(self, account_number, balance, interest_rate):
        super().__init__(account_number, balance)
        self.interest_rate = interest_rate

    def add_interest(self):
        interest = self.balance * (self.interest_rate / 100)
        self.balance += interest
        print(f"Interest Added: {interest}, New Balance: {self.balance}")

savings = SavingsAccount("123456789", 10000, 5)
savings.deposit(2000)
savings.withdraw(3000)
savings.add_interest()
print("Name: Aanit Brahma")
print("Roll Number: 2430601")

Deposited: 2000, New Balance: 12000
Withdrawn: 3000, Remaining Balance: 9000
Interest Added: 450.0, New Balance: 9450.0
Name: Aanit Brahma
Roll Number: 2430601