In [ ]:
import math

class Shape:
    def area(self):
        pass

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius
    def area(self):
        return math.pi * self.radius * self.radius

class Rectangle(Shape):
    def __init__(self, length, width):
        self.length = length
        self.width = width
    def area(self):
        return self.length * self.width

class Triangle(Shape):
    def __init__(self, base, height):
        self.base = base
        self.height = height
    def area(self):
        return 0.5 * self.base * self.height

shapes = [Circle(5), Rectangle(4, 6), Triangle(3, 8)]
for shape in shapes:
    print(f"Area: {shape.area()}")

class Vehicle:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year
    def display_info(self):
        print(f"Make: {self.make}, Model: {self.model}, Year: {self.year}")

class Car(Vehicle):
    def __init__(self, make, model, year, mileage):
        super().__init__(make, model, year)
        self.mileage = mileage
    def display_info(self):
        super().display_info()
        print(f"Mileage: {self.mileage} km")

car = Car("Toyota", "Corolla", 2020, 15000)
car.display_info()
print("Name: Aanit Brahma")
print("Roll Number: 2430601")

Area: 78.53981633974483
Area: 24
Area: 12.0
Make: Toyota, Model: Corolla, Year: 2020
Mileage: 15000 km
Name: Aanit Brahma
Roll Number: 2430601

In [ ]:
class Animal:
    def make_sound(self):
        pass

class Dog(Animal):
    def make_sound(self):
        return "Woof Woof!"

class Cat(Animal):
    def make_sound(self):
        return "Meow Meow!"

class Cow(Animal):
    def make_sound(self):
        return "Moo Moo!"

animals = [Dog(), Cat(), Cow()]
for animal in animals:
    print(f"{animal.__class__.__name__} Sound: {animal.make_sound()}")

class Vehicle:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year
    def display_info(self):
        print(f"Make: {self.make}, Model: {self.model}, Year: {self.year}")

class Car(Vehicle):
    def __init__(self, make, model, year, mileage):
        super().__init__(make, model, year)
        self.mileage = mileage
    def display_info(self):
        super().display_info()
        print(f"Mileage: {self.mileage} km")

car = Car("Toyota", "Corolla", 2020, 15000)
car.display_info()
print("Name: Aanit Brahma")
print("Roll Number: 2430601")

Dog Sound: Woof Woof!
Cat Sound: Meow Meow!
Cow Sound: Moo Moo!
Make: Toyota, Model: Corolla, Year: 2020
Mileage: 15000 km
Name: Aanit Brahma
Roll Number: 2430601

In [ ]:
class Employee:
    def calculate_pay(self):
        pass

class HourlyEmployee(Employee):
    def __init__(self, name, hourly_rate, hours_worked):
        self.name = name
        self.hourly_rate = hourly_rate
        self.hours_worked = hours_worked
    def calculate_pay(self):
        return self.hourly_rate * self.hours_worked

class SalariedEmployee(Employee):
    def __init__(self, name, annual_salary):
        self.name = name
        self.annual_salary = annual_salary
    def calculate_pay(self):
        return self.annual_salary / 12

employees = [
    HourlyEmployee("John", 20, 160),
    SalariedEmployee("Alice", 60000)
]

for employee in employees:
    print(f"{employee.name}'s Payment: {employee.calculate_pay()}")

class Vehicle:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year
    def display_info(self):
        print(f"Make: {self.make}, Model: {self.model}, Year: {self.year}")

class Car(Vehicle):
    def __init__(self, make, model, year, mileage):
        super().__init__(make, model, year)
        self.mileage = mileage
    def display_info(self):
        super().display_info()
        print(f"Mileage: {self.mileage} km")

car = Car("Toyota", "Corolla", 2020, 15000)
car.display_info()
print("Name: Aanit Brahma")
print("Roll Number: 2430601")

John's Payment: 3200
Alice's Payment: 5000.0
Make: Toyota, Model: Corolla, Year: 2020
Mileage: 15000 km
Name: Aanit Brahma
Roll Number: 2430601

In [ ]:
class Employee:
    def calculate_pay(self):
        pass

class HourlyEmployee(Employee):
    def __init__(self, name, hourly_rate, hours_worked):
        self.name = name
        try:
            self.hourly_rate = float(hourly_rate)
            self.hours_worked = float(hours_worked)
            if self.hourly_rate < 0 or self.hours_worked < 0:
                raise ValueError("Hourly rate and hours worked must be non-negative.")
        except ValueError as e:
            print(f"Invalid input: {e}")
            self.hourly_rate = 0
            self.hours_worked = 0

    def calculate_pay(self):
        return self.hourly_rate * self.hours_worked

class SalariedEmployee(Employee):
    def __init__(self, name, annual_salary):
        self.name = name
        try:
            self.annual_salary = float(annual_salary)
            if self.annual_salary < 0:
                raise ValueError("Annual salary must be non-negative.")
        except ValueError as e:
            print(f"Invalid input: {e}")
            self.annual_salary = 0

    def calculate_pay(self):
        return self.annual_salary / 12

employees = [
    HourlyEmployee("John", 20, 160),
    SalariedEmployee("Alice", 60000),
    HourlyEmployee("Bob", -15, 150),  # Invalid input example
    SalariedEmployee("Eve", "invalid")  # Invalid input example
]

for employee in employees:
    print(f"{employee.name}'s Payment: {employee.calculate_pay()}")

class Vehicle:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year
    def display_info(self):
        print(f"Make: {self.make}, Model: {self.model}, Year: {self.year}")

class Car(Vehicle):
    def __init__(self, make, model, year, mileage):
        super().__init__(make, model, year)
        self.mileage = mileage
    def display_info(self):
        super().display_info()
        print(f"Mileage: {self.mileage} km")

car = Car("Toyota", "Corolla", 2020, 15000)
car.display_info()
print("Name: Aanit Brahma")
print("Roll Number: 2430601")

Invalid input: Hourly rate and hours worked must be non-negative.
Invalid input: could not convert string to float: 'invalid'
John's Payment: 3200.0
Alice's Payment: 5000.0
Bob's Payment: 0
Eve's Payment: 0.0
Make: Toyota, Model: Corolla, Year: 2020
Mileage: 15000 km
Name: Aanit Brahma
Roll Number: 2430601

In [ ]:
class MediaPlayer:
    def play(self):
        pass

class AudioPlayer(MediaPlayer):
    def __init__(self, file_name):
        self.file_name = file_name

    def play(self):
        print(f"Playing audio file: {self.file_name}")

class VideoPlayer(MediaPlayer):
    def __init__(self, file_name):
        self.file_name = file_name

    def play(self):
        print(f"Playing video file: {self.file_name}")

media_files = [
    AudioPlayer("song.mp3"),
    VideoPlayer("movie.mp4"),
    AudioPlayer("podcast.wav")
]

for media in media_files:
    media.play()

class Vehicle:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year
    def display_info(self):
        print(f"Make: {self.make}, Model: {self.model}, Year: {self.year}")

class Car(Vehicle):
    def __init__(self, make, model, year, mileage):
        super().__init__(make, model, year)
        self.mileage = mileage
    def display_info(self):
        super().display_info()
        print(f"Mileage: {self.mileage} km")

car = Car("Toyota", "Corolla", 2020, 15000)
car.display_info()
print("Name: Aanit Brahma")
print("Roll Number: 2430601")

Playing audio file: song.mp3
Playing video file: movie.mp4
Playing audio file: podcast.wav
Make: Toyota, Model: Corolla, Year: 2020
Mileage: 15000 km
Name: Aanit Brahma
Roll Number: 2430601