In [ ]:
class Student:
    def __init__(self, name, age, grade):
        self.name = name
        self.age = age
        self.grade = grade

    def display(self):
        print(f"Name: {self.name}, Age: {self.age}, Grade: {self.grade}")

student = Student("Alice", 20, "A")
student.display()

Name: Alice, Age: 20, Grade: A

In [ ]:
class Student:
    def __init__(self, name, age, grade):
        self.name = name
        self.age = age
        self.grade = grade

    def talk(self):
        print(f"Name: {self.name}, Age: {self.age}, Grade: {self.grade}")

student = Student("Bob", 21, "B")
student.talk()

Name: Bob, Age: 21, Grade: B

In [ ]:
class Rectangle:
    def __init__(self, length, width):
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width

    def perimeter(self):
        return 2 * (self.length + self.width)

rectangle = Rectangle(5, 3)
print(rectangle.area())
print(rectangle.perimeter())

15
16

In [ ]:
class BankAccount:
    def __init__(self, balance=0):
        self.__balance = balance

    def deposit(self, amount):
        self.__balance += amount

    def withdraw(self, amount):
        if amount <= self.__balance:
            self.__balance -= amount

    def check_balance(self):
        return self.__balance

account = BankAccount(1000)
account.deposit(500)
account.withdraw(200)
print(account.check_balance())

1300

In [ ]:
class Movie:
    def __init__(self, title, actor, actress):
        self.title = title
        self.actor = actor
        self.actress = actress

    def display(self):
        print(f"Title: {self.title}, Actor: {self.actor}, Actress: {self.actress}")

movies = []
while True:
    title = input("Enter movie title: ")
    actor = input("Enter actor name: ")
    actress = input("Enter actress name: ")
    movies.append(Movie(title, actor, actress))
    if input("Add another movie? (Yes/No): ").lower() == "no":
        break

for movie in movies:
    movie.display()

Enter movie title: tere naam
Enter actor name: salmaan khan
Enter actress name: aishwariya
Add another movie? (Yes/No): no
Title: tere naam , Actor: salmaan khan, Actress: aishwariya

In [ ]:
import math

class Shape:
    def area(self):
        pass

    def perimeter(self):
        pass

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return math.pi * self.radius ** 2

    def perimeter(self):
        return 2 * math.pi * self.radius

class Square(Shape):
    def __init__(self, side):
        self.side = side

    def area(self):
        return self.side ** 2

    def perimeter(self):
        return 4 * self.side

circle = Circle(5)
square = Square(4)
print(circle.area(), circle.perimeter())
print(square.area(), square.perimeter())

78.53981633974483 31.41592653589793
16 16

In [ ]:
class Book:
    def __init__(self, title, author, price):
        self.title = title
        self.author = author
        self.price = price

    def get_details(self):
        return f"Title: {self.title}, Author: {self.author}, Price: {self.price}"

book = Book("Python Basics", "John Doe", 499)
print(book.get_details())

Title: Python Basics, Author: John Doe, Price: 499

In [ ]:
class Vehicle:
    def __init__(self, name, mileage):
        self.name = name
        self.mileage = mileage

    def display(self):
        return f"Vehicle: {self.name}, Mileage: {self.mileage} kmpl"

class Car(Vehicle):
    pass

class Truck(Vehicle):
    pass

class Motorcycle(Vehicle):
    pass

car = Car("Sedan", 15)
truck = Truck("Freightliner", 8)
motorcycle = Motorcycle("Yamaha", 40)
print(car.display())
print(truck.display())
print(motorcycle.display())

Vehicle: Sedan, Mileage: 15 kmpl
Vehicle: Freightliner, Mileage: 8 kmpl
Vehicle: Yamaha, Mileage: 40 kmpl

In [ ]:
class TodoList:
    def __init__(self):
        self.tasks = []

    def add_task(self, task):
        self.tasks.append(task)

    def remove_task(self, task):
        if task in self.tasks:
            self.tasks.remove(task)

    def display_tasks(self):
        return self.tasks

todo = TodoList()
todo.add_task("Complete homework")
todo.add_task("Go to the gym")
todo.remove_task("Complete homework")
print(todo.display_tasks())

['Go to the gym']

In [ ]:
class Bank:
    def __init__(self):
        self.accounts = {}

    def add_account(self, account_number, balance):
        self.accounts[account_number] = balance

    def remove_account(self, account_number):
        if account_number in self.accounts:
            del self.accounts[account_number]

    def total_balance(self):
        return sum(self.accounts.values())

bank = Bank()
bank.add_account(101, 5000)
bank.add_account(102, 10000)
bank.remove_account(101)
print(bank.total_balance())

10000

In [ ]:
class Product:
    def __init__(self, name, price, quantity):
        self.name = name
        self.price = price
        self.quantity = quantity

    def total_cost(self):
        return self.price * self.quantity

    def update_quantity(self, new_quantity):
        self.quantity = new_quantity

product = Product("Laptop", 50000, 2)
print(product.total_cost())
product.update_quantity(3)
print(product.total_cost())

100000
150000

In [ ]:
class Employee:
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary

    def display(self):
        return f"Name: {self.name}, Salary: {self.salary}"

class Manager(Employee):
    def __init__(self, name, salary, bonus):
        super().__init__(name, salary)
        self.bonus = bonus

    def total_salary(self):
        return self.salary + self.bonus

class Developer(Employee):
    def __init__(self, name, salary, projects):
        super().__init__(name, salary)
        self.projects = projects

    def display(self):
        return f"Name: {self.name}, Salary: {self.salary}, Projects: {self.projects}"

class Tester(Employee):
    def __init__(self, name, salary, bugs_found):
        super().__init__(name, salary)
        self.bugs_found = bugs_found

    def display(self):
        return f"Name: {self.name}, Salary: {self.salary}, Bugs Found: {self.bugs_found}"

manager = Manager("Alice", 80000, 20000)
developer = Developer("Bob", 60000, ["Project A", "Project B"])
tester = Tester("Charlie", 50000, 50)

print(manager.total_salary())
print(developer.display())
print(tester.display())

100000
Name: Bob, Salary: 60000, Projects: ['Project A', 'Project B']
Name: Charlie, Salary: 50000, Bugs Found: 50